Implement the Action
lazybytez/sync-markdown-bookstack-action pull request #2
Opened 2023-09-21 20:06 UTC by pascal-zarrad

## Description
Implement the first version of the Action

## How can this be tested?
tbd...

2023-09-22 22:08 UTC, pascal-zarrad commented
We will fix linter issues in a follow-up PR.
Code Style is already fine as Prettier is used during bundling.

2023-09-24 14:39 UTC, elias-knodel requested changes

2023-09-24 14:39 UTC, elias-knodel commented on README.md
> +[gh-stars-badge]: https://img.shields.io/github/stars/lazybytez?style=for-the-badge&colorA=302D41&colorB=f9e2af
```suggestion
[gh-stars-badge]: https://img.shields.io/github/stars/lazybytez/sync-markdown-bookstack-action?style=for-the-badge&colorA=302D41&colorB=f9e2af
```

2023-09-24 14:43 UTC, elias-knodel approved these changes
LGTM :+1:

2023-09-24 14:44 UTC, merged